spring:
  thymeleaf:
    cache: false
  resources:
    static-locations: classpath:/templates/  #与 thymeleaf 目录重合, 以实现与本地页面编写中的资源目录一致性

logging:
  level:
    root: INFO
    net.thinkbase.dev.gittools: DEBUG